name: API CI

on: [push, pull_request]

jobs:
  style:
    name: Check style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v1.1.1
        with:
          python-version: "3.7.6"
      - name: Cache pip dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt black isort
        working-directory: "./api"
      - name: Run black
        run: python -m black --check .
        working-directory: "./api"
      - name: Check import order
        run: python -m isort -y
        working-directory: "./api"
