name: Client CI

on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Setup Node.js for use with Actions
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.0"
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: client/${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies with Yarn
        run: yarn install
        working-directory: "./client"
      - name: Next.js build
        run: yarn run build
        working-directory: "./client"
      - name: Export static site
        run: yarn run export
        working-directory: "./client"
      - name: Upload static site
        uses: actions/upload-artifact@v1
        with:
          name: static-site
          path: client/out
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Setup Node.js for use with Actions
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.0"
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: client/${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies with Yarn
        run: yarn install
        working-directory: "./client"
      - name: Lint
        run: yarn run lint
        working-directory: "./client"
  style:
    name: Check style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Setup Node.js for use with Actions
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.0"
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: client/${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies with Yarn
        run: yarn install
        working-directory: "./client"
      - name: Check style with Prettier
        run: yarn run style
        working-directory: "./client"
